/**
 * Utility functions for Calendar (.ics) and Task integration
 */
import { ActionItem } from '../types';

/**
 * Format a Date object into ICS iCalendar timestamp (YYYYMMDDTHHMMSSZ in UTC)
 */
export function formatIcsDate(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  const hh = String(date.getUTCHours()).padStart(2, '0');
  const mm = String(date.getUTCMinutes()).padStart(2, '0');
  const ss = String(date.getUTCSeconds()).padStart(2, '0');
  return `${y}${m}${d}T${hh}${mm}${ss}Z`;
}

/**
 * Clean text for standard RFC 5545 iCalendar (.ics) escaping
 * Escapes backslashes, semicolons, commas, and normalizes line breaks to \n
 */
export function escapeIcsText(text: string): string {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * RFC 5545 Line Folding helper: lines longer than 75 characters are folded
 * by inserting CRLF followed by a space
 */
export function foldIcsLine(line: string, maxLength = 75): string {
  if (line.length <= maxLength) return line;
  const chunks: string[] = [];
  chunks.push(line.slice(0, maxLength));
  let i = maxLength;
  while (i < line.length) {
    chunks.push(' ' + line.slice(i, i + maxLength - 1));
    i += maxLength - 1;
  }
  return chunks.join('\r\n');
}

/**
 * Generate a standard iCalendar (.ics) file string for a list of action items
 */
export function generateIcsCalendarFile(
  title: string,
  actionItems: ActionItem[],
  sessionSummary?: string
): string {
  const now = new Date();
  const dtStamp = formatIcsDate(now);
  const safeTitle = escapeIcsText(title || 'Personal Reflection');
  const safeSummary = sessionSummary ? escapeIcsText(sessionSummary) : '';

  const events = actionItems.map((item, idx) => {
    // Default scheduled time: tomorrow morning 9:00 AM + idx hours
    const startDate = item.dueDate ? new Date(item.dueDate) : new Date(now.getTime() + (idx + 1) * 24 * 60 * 60 * 1000);
    startDate.setHours(9 + (idx % 8), 0, 0, 0);

    const endDate = new Date(startDate.getTime() + 45 * 60 * 1000); // 45 min duration
    const uid = `gemini-action-${item.id}-${Date.now()}@geminijournal.app`;

    const priorityVal = item.priority === 'high' ? '1' : item.priority === 'medium' ? '5' : '9';
    const safeItemText = escapeIcsText(item.text);
    const description = safeSummary
      ? `Action item from reflection: ${safeTitle}\\n\\nContext: ${safeSummary}`
      : `Action item from reflection session: ${safeTitle}`;

    const eventLines = [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${dtStamp}`,
      `DTSTART:${formatIcsDate(startDate)}`,
      `DTEND:${formatIcsDate(endDate)}`,
      `SUMMARY:${safeItemText} [${item.priority.toUpperCase()}]`,
      `DESCRIPTION:${description}`,
      `PRIORITY:${priorityVal}`,
      'STATUS:NEEDS-ACTION',
      'TRANSP:OPAQUE',
      'BEGIN:VALARM',
      'TRIGGER:-PT15M',
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${safeItemText}`,
      'END:VALARM',
      'END:VEVENT',
    ];

    return eventLines.map((line) => foldIcsLine(line)).join('\r\n');
  });

  const icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Google AI Studio//Personal Gemini Journal//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    foldIcsLine(`X-WR-CALNAME:${safeTitle} - AI Action Deliverables`),
    foldIcsLine(`X-WR-CALDESC:Action items generated by Gemini Wisdom Matrix`),
    ...events,
    'END:VCALENDAR',
  ];

  return icsLines.join('\r\n');
}

/**
 * Trigger browser download of the generated .ics file
 */
export function downloadIcsFile(title: string, actionItems: ActionItem[], sessionSummary?: string) {
  if (!actionItems || actionItems.length === 0) return;
  const icsContent = generateIcsCalendarFile(title, actionItems, sessionSummary);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const safeFilename = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  link.download = `${safeFilename}_actions.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export tasks formatted as a Todo list Markdown / Text
 */
export function exportTasksToText(title: string, actionItems: ActionItem[]): string {
  let output = `# Action Plan: ${title}\n\n`;
  output += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
  actionItems.forEach((act, idx) => {
    output += `- [${act.completed ? 'x' : ' '}] (${act.priority.toUpperCase()}) ${act.text}\n`;
  });
  return output;
}
